name: Development Registry
summary: Registry containing resources (artifacts) used in development environments.
url: https://apicurio-registry-mt-apicurio-apicurio-registry.apps.smaug.na.operate-first.cloud/t/4d942fef-e143-477f-aacd-f8c3c7d436eb/apis/registry/v2
credentials:
  username: service-account-gitops
  password: ${SA_PASSWORD}
rules:
  validity: FULL
  compatibility: BACKWARD
roles:
  - principal: bwayne
    role: DEVELOPER
  - principal: ckent
    role: ADMIN
  - principal: dprince
    role: ADMIN
  - principal: enigma
    role: READ-ONLY
  - principal: sa-app-1
    role: READ-ONLY
  - principal: sa-app-2
    role: READ-ONLY
  - principal: sa-app-3
    role: READ-ONLY
settings:
  - name: registry.ccompat.legacy-id-mode.enabled
    value: false
  - name: registry.auth.basic-auth-client-credentials.enabled
    value: true
